SELECT DISTINCT
SFRSTCR_TERM_CODE,
SPRIDEN_ID,
GOBTPAC_EXTERNAL_USER,
SPRIDEN_LAST_NAME AS STUDENT_LAST_NAME,
SPRIDEN_FIRST_NAME AS STUDENT_FIRST_NAME,


--SQ FOR PHONE AREA CODE
(SELECT A.SPRTELE_PHONE_AREA 
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'CE'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'CE')) AS SPRTELE_PHONE_AREA_CE,


--SQ FOR PHONE NUMBER
(SELECT A.SPRTELE_PHONE_NUMBER 
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'CE'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'CE')) AS SPRTELE_PHONE_NUMBER_CE,

(SELECT A.SPRTELE_PHONE_AREA 
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'MA'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'MA')) AS SPRTELE_PHONE_AREA_MA,


--SQ FOR PHONE NUMBER
(SELECT A.SPRTELE_PHONE_NUMBER 
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'MA'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'MA')) AS SPRTELE_PHONE_NUMBER_MA,

--SQ TO CONCAT AREA AND PHONE NUMBER; NO HYPHEN NEEDED

(SELECT TRIM(A.SPRTELE_PHONE_AREA || A.SPRTELE_PHONE_NUMBER) --REMOVE EVERYTHING BUT CHARACTER STRING OF NUMBERS
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'CE'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'CE')) AS STUDENT_PHONE_CE,

(SELECT TRIM(A.SPRTELE_PHONE_AREA || A.SPRTELE_PHONE_NUMBER) --REMOVE EVERYTHING BUT CHARACTER STRING OF NUMBERS
FROM SPRTELE A
WHERE A.SPRTELE_PIDM = SPRIDEN_PIDM
AND A.SPRTELE_TELE_CODE = 'MA'
AND A.SPRTELE_SEQNO = (SELECT MAX(B.SPRTELE_SEQNO) 
FROM SPRTELE B 
WHERE B.SPRTELE_PIDM = SPRIDEN_PIDM
AND B.SPRTELE_TELE_CODE = 'MA')) AS STUDENT_PHONE_MA,


 --SQ FOR EMAIL
(SELECT GOBTPAC_EXTERNAL_USER 
FROM GOBTPAC 
WHERE GOBTPAC_PIDM = SFRSTCR_PIDM) || '@cctech.edu' AS STUDENT_EMAIL


FROM SFRSTCR

JOIN SSBSECT
ON SSBSECT_CRN = SFRSTCR_CRN 
AND SSBSECT_TERM_CODE = SFRSTCR_TERM_CODE

JOIN SGBSTDN
ON SGBSTDN_PIDM = SFRSTCR_PIDM

JOIN SPRIDEN
ON SPRIDEN_PIDM = SFRSTCR_PIDM

JOIN GOBTPAC
ON GOBTPAC_PIDM = SFRSTCR_PIDM

WHERE SFRSTCR_RSTS_CODE IN ('RE','RW','AU','AW','WS','WM')
AND SPRIDEN_CHANGE_IND IS NULL
AND SGBSTDN_TERM_CODE_EFF = (SELECT MAX(A.SGBSTDN_TERM_CODE_EFF)
                             FROM SGBSTDN A
                             WHERE A.SGBSTDN_PIDM = SFRSTCR_PIDM
                             AND A.SGBSTDN_TERM_CODE_EFF <= SFRSTCR_TERM_CODE)
AND SFRSTCR_TERM_CODE = 202420 -- 2826 FOR 202410; 2612 FOR 202420 -> CHANGE TERM FOR headcount
